name: wikidata_sync
on:
  push:
    branches:
      - main
jobs:
  wikidata_sync:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: install libs
      run: pip install wikibaseintegrator pandas
    - name: script
      uses: jannekem/run-python-script-action@v1
      with:
        script: |

          import json
          import pathlib
          import subprocess
          
          with open(pathlib.Path.cwd() / 'bot_login.json', 'w') as login:
            json.dump({"user":"${{secrets.WIKIDATA_USERNAME}}", "pass":"${{secrets.WIKIDATA_PASSWORD}}"}, login)
          
          subprocess.call(['python', 'acmi_bot.py'])
