name: wikidata_sync
on:
  push:
    branches:
      - main
jobs:
  wikidata_sync:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      env:
        wd_username: ${{ secrets.WIKIDATA_USERNAME }}
        wd_password: ${{ secrets.WIKIDATA_PASSWORD }}
    - name: do something
      run: |
          jq -n '{"test":"${{ secrets.WIKIDATA_USERNAME }}"}' > hello.json
          ls -al
