name: taskrunner
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: script
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          
          # import libraries
          
          import pathlib
          
          for x in pathlib.Path.cwd().iterdir():
            print(x)
  
          with open(pathlib.Path.cwd() / 'bot_login.json', 'w') as login:
            json.dump({"user":"$WIKIDATA_USERNAME", "pass":"$WIKIDATA_PASSWORD"}, login)
            
          for x in pathlib.Path.cwd().iterdir():
            print(x)
