name: wikidata_sync
on:
  push:
    branches:
      - main
jobs:
  wikidata_sync:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      env:
        wd_username: ${{ secrets.WIKIDATA_USERNAME }}
        wd_password: ${{ secrets.WIKIDATA_PASSWORD }}
    - name: do something
      run: |
          # jq -n '{"user":"${{ secrets.WIKIDATA_USERNAME }}","pass":"${{ secrets.WIKIDATA_PASSWORD }}"}' > bot_login.json
          # pip3 install pandas pydash wikibaseintegrator
          # python3 acmi_bot.py
          
          ls -al
          jq -n '{"user":"${{ secrets.WIKIDATA_USERNAME }}"}' > bot_login.json
          echo bot_login.json
